### ISSUE TITLE
Incorrect app recognition with more than 2 apps from Steam open

### ISSUE THREAD

**Issue by NilaierMusic** [1A3Dev/LC-RecentlyPlayedWith#1]
If you have more than just Lethal Company open from Steam, the mod can incorrectly recognize the app you've played with other people, resulting in an incorrect game being displayed.

Blurred avatars and nicknames for people's privacy:
![steamwebhelper_Snk0a0z3QJ](https://github.com/1A3Dev/LC-RecentlyPlayedWith/assets/86863646/ecfb1c75-8ef8-4c75-ad62-cac10b019736)

**Comment by 1A3Dev** [comment]
This is actually an issue with steam and not the mod, I have the same issue myself with it showing Soundpad (the soundboard I use) instead of Lethal Company. I've already reported it to steam who are aware of the issue.

![1704837367](https://github.com/1A3Dev/LC-RecentlyPlayedWith/assets/23743032/17e1842e-3a85-48a1-8ec6-d8c075b22462)
